# Generated by Django 3.0.4 on 2020-03-19 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bitrix_id', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.CharField(max_length=255)),
                ('flat_count', models.IntegerField(default=0)),
                ('actual_date', models.DateTimeField(null=True)),
                ('reestr_link', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('square', models.FloatField(null=True)),
                ('rights', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('LEGAL_FACE', 'Юр. лицо'), ('PHYSICAL_FACE', 'Физ. лицо')], max_length=50)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reestrdoma_app.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cad_num', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, null=True)),
                ('square', models.FloatField(null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('xml_link', models.CharField(max_length=255, null=True)),
                ('zip_link', models.CharField(max_length=255, null=True)),
                ('html_link', models.CharField(max_length=255, null=True)),
                ('xml_link_status', models.CharField(max_length=255, null=True)),
                ('zip_link_status', models.CharField(max_length=255, null=True)),
                ('html_link_status', models.CharField(max_length=255, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reestrdoma_app.House')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reestrdoma_app.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reestrdoma_app.Profile'),
        ),
    ]
